evalplus/eval/__init__.py, evalplus/evaluate.py
cc: @tju01
As a quick workaround, allow users to set a minimal time limit from command-line and increase the minimal timeout to 100 milliseconds.
link: #5
=> Add flag min_time_limit to evalutor

evalplus/eval/__init__.py, evalplus/evaluate.py
Users are allowed to fully configure the time limit. If `gt_multiplier=K`, then the time limit would be `max(min_time_limit, K * gt_time)`.
Partly resolve #5.
=> add flag `gt_multiplier` to evaluator

groundtruth/mbpp/012.py
Add additional checks: a matrix should be a non-empty list of non-empty lists of equal length.
=> contract[mbpp]: 012

tools/sanitize.py
Before the `maxsplit=1` fix, the sanitizer would be unsound in some case, e.g. a solution like the following one:
```python
def f(n):
def factorial(i):
...
```
When sanitizing this code, the variable `def_left` would match both `def f` and `def factorial`, and then this code would be split into 3 parts, and the original logic would drop `def f` and keep `def factorial` when doing `new_code.split(def_left)[-1]`.
=> Fix sanitizer loading and sanitizing issue

.gitignore, tools/humaneval/convert.py, tools/humaneval/to_original_fmt.py
this pr tries to implement features mentioned in #55 
this pr tried to implement feat mentioned in #55 
HumanEval
use WizardCoder samples(https://github.com/evalplus/evalplus/releases/download/v0.1.0/wizardcoder-34b.json) to test
use evalplus:
use humaneval with compatible dataset:
we can get same results :)
=> feat[port]: port HumanEval+ to the original HumanEval format 

evalplus/eval/__init__.py, tools/mbpp/to_original_fmt.py
This pr tried to implement feat mentioned in #55 
MbppPlus part
Use released gpt-4's samples (https://github.com/evalplus/evalplus/releases/download/v0.2.0/gpt-4-1106-preview_temp_0.0.zip) and converted into a json file.
Compiled dataset and samples can be used in Human-eval framework right now.
Also used evalplus to validate the results.
- Inconsistent task: "Mbpp/56" has entry point named "check", which introduces conflict with test code.
=> feat[port]: port MBPP+ to the original-MBPP-like format

tools/sanitize.py
When sanitizing samples with an empty solution, 
It adds the def_code, which is unexpected,
We should skip this case.
=> fix: skip empty solutions

codegen/model.py
`direct_completion` has to be **True** for magicoder for codegen/generate.py script after recent fixes #143 #142 
These changes were made for the issue #141 
Able to reproduce score for **magicoder-s-ds-6.7b** with these changes
> humaneval (base tests)
> pass@1: 0.756
> humaneval+ (base + extra tests)
> pass@1: 0.707
=> Magicoder direct_completion fix

evalplus/eval/__init__.py, tools/humaneval/to_original_fmt.py, tools/mbpp/to_original_fmt.py
trying to fix #157
use `np.allclose` instead of `np.testing.assert_allclose` to avoid creating a subprocess
```shell
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.Popen = None
>>> import numpy as np
>>> assert np.allclose([1, 2], [1, 2])
>>> assert np.allclose([1, 2], [1, 1])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AssertionError
>>> np.testing
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/junhao/miniconda3/envs/evalperf/lib/python3.10/site-packages/numpy/__init__.py", line 327, in __getattr__
import numpy.testing as testing
File "/home/junhao/miniconda3/envs/evalperf/lib/python3.10/site-packages …
```
=> fix(eval): use `assert np.allclose` to replace `np.testing.assert_allclose`

evalplus/eval/__init__.py
Previously, without `--test-details`, the evaluation results do not even show the first failed case, which is inconvenient for debugging.
=> fix: show the first failed case when `--test-details` is not enabled

evalplus/eval/__init__.py, evalplus/evaluate.py
Fix the following issues:
```python
import numpy as np
assert all(isinstance(i, float) for i in []) == True
assert np.allclose([], [1.1], rtol=1e-07, atol=1e-6) == True
assert np.allclose(1.1, [1.1], rtol=1e-07, atol=1e-6) == True
```
=> fix: showing the only and the last fail test, `is_float`

codegen/model.py
Just a typo `correpsonding` -> `corresponding` , but it may slightly affect model performance.
=> fix: chat template response typo

evalplus/eval/__init__.py
- Should use `abs` to make sure the result is near zero.
- Should use `continue` to skip the following regular checks for other problems. Otherwise, even a correct one passes this assertion, it may fail when applying other checks which are incompatible to this problem.
=> fix: correctness check for `find_zero`

evalplus/eval/__init__.py, evalplus/eval/_special_oracle.py, tools/mbpp/to_original_fmt.py
fix #210 
Add special oracles for 
- Mbpp/581 
- Mbpp/558 
They have more than one solutions which could be accepted.
=> fix(mbpp): add special oracles

evalplus/evaluate.py
Added `pass_at_k` dicts (base and plus if available) to `result` for reusing calculated pass@k in external tools, etc.
=> feat(eval): Saving pass@k in result output

evalplus/provider/gptqmodel.py
Based on our ci tests, some torch versions contain incomplete,bad implementations of `torch.mps` and `torch.xpu`
On some version of torch, `torch.mps` exists but not `torch.mps.is_available()` which is extremely strange.
=> [GPTQModel] Fix torch compat with bad implementation of mps, xpu

evalplus/provider/hf.py, evalplus/provider/vllm.py
For some models, when loading the HF tokenizer with `use_fast=False`, `AutoTokenizer.from_pretrained(xxx, use_fast=False)` returns a boolean
```
>>> tok = AutoTokenizer.from_pretrained("unsloth/Llama-4-Scout-17B-16E-Instruct-unsloth-bnb-4bit", use_fast=False)
>>> tok
False
>>> 
```
Thus breaking the evalplus code later on. 
This PR fixes this issue by avoid passing the parameter `use_fast`. The code will still remain compatible with GGUF models since the default `use_fast` is used anyway if `gguf_file` is passed.
To repro the issue:
```bash
evalplus.evaluate --model meta-llama/Llama-4-Scout-17B-16E-Instruct --trust_remote_code True --dtype bfloat16 --backend vllm --tp 8 --attn_implementation sdpa --greedy  --bs 2 --dataset humaneval --root /tmp/tmpr2p3dtyn
```
=> fix: fix issue with HF tokenizer

evalplus/eval/utils.py
The Python built-in `resource` package is only available on UNIX systems, rendering this entire evaluation system unable to run on Windows.
This PR allows execution, albeit being less safe, on Windows.
=> feat: allow unsafe Windows execution

docs/cli.md
This PR fixed the broken URL for Program Execution in EvalPlus and EvalPerf.
=> Fix a broken url in cli.md

evalplus/codegen.py, evalplus/provider/__init__.py, evalplus/provider/openai.py
This PR adds a verify_certificate parameter (defaulting to True) to support custom model URLs with self-signed or invalid SSL certificates. Currently, strict certificate validation blocks such connections, preventing evaluations from running. By setting verify_certificate=False, users can bypass SSL verification when needed.
=> Allow bypassing SSL verification for custom model URLs
